version: "2"

services:
  flask:
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    #    image: hello_nlp
    image: registry.cn-shenzhen.aliyuncs.com/luler/hello_nlp
    ports:
      - 5000:5000
    volumes:
      - ./:/root/work